# Generated by Django 2.1.7 on 2020-02-03 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200203_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 2, 3, 20, 55, 48, 396937)),
        ),
    ]
